spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/digital_bank_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate.ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect