CREATE TABLE account
(
    id      BIGINT PRIMARY KEY,
    balance BIGINT       NOT NULL,
    name    VARCHAR(255) NOT NULL
);

CREATE SEQUENCE account_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE CACHE 1;